[package]
name = "address-artisan"
version = "0.1.1"
description = "A tool for generating vanity P2PKH Bitcoin addresses."
authors = ["Marcus Lacerda <marcuslacerda@tutamail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/seaasses/address-artisan"
edition = "2021"


[dependencies]
bs58 = "0.5.1"
clap = { version = "4.5.27", features = ["derive"] }
rand = "0.9.0"
secp256k1 = { version = "0.29.1", features = ["rand-std"] }
sha2 = "0.10.8"
ripemd = "0.1.3"
hmac = "0.12.1"
threadpool = "1.8.1"
